name: build
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        NDK:
#          - 21.4.7075529
#          - 22.0.7026061
#          - 22.1.7171670
          - 23.0.7599858
        CMake:
#          - 3.10.2.4988404
#          - 3.18.1
          - 3.21.1
        minSdk:
#          - 16
#          - 19
          - 20
#          - 21
#          - 31
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - run: echo "" >> app/build.gradle
      - run: echo "android.ndkVersion '${{ matrix.NDK }}'" >> app/build.gradle
      - run: perl -pe "s/version '[\d\.]+'/version '${{ matrix.CMake }}'/" -i app/build.gradle
      - run: perl -pe "s/minSdk \d+$/minSdk ${{ matrix.minSdk }}/" -i app/build.gradle

      - run: cat app/build.gradle

      - run: ./gradlew build
